name: Develop Workflow

on:
  pull_request:
    branches:
      - develop

jobs:
  # Trabajo para construir y probar la aplicación
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Cambia a la versión de Node.js que uses en el proyecto

      - name: Install dependencies
        run: npm install

      - name: Lint the code
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build Next.js app
        run: npm run build

  # Trabajo opcional para desplegar en un entorno de staging después de la fusión
  deploy-to-staging:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event.pull_request.merged == true  # Solo se despliega si el PR ha sido fusionado
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Deploy to Staging
        env:
          STAGING_URL: ${{ secrets.STAGING_URL }}
          STAGING_API_KEY: ${{ secrets.STAGING_API_KEY }}
        run: |
          # Comandos específicos para tu despliegue
          # Ejemplo: despliegue en Vercel, AWS o servidor custom
          npx next export
          curl -X POST -H "Authorization: Bearer $STAGING_API_KEY" -d "targetUrl=${{ secrets.STAGING_URL }}" -d "projectPath=./out"
